apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-data
spec:
  instances: {{ .Values.pgData.instances }}
  imageName: {{ .Values.pgData.imageName }}
  storage:
    size: {{ .Values.pgData.storage.size }}
    storageClass: {{ .Values.pgData.storage.storageClass }}
  bootstrap:
    initdb:
      database: maritime
      owner: maritime
      postInitSQL:
        {{- range .Values.pgData.postInitSQL }}
        - {{ . | quote }}
        {{- end }}
  postgresql:
    parameters:
      shared_buffers: "256MB"
      max_connections: "200"
      max_worker_processes: "16"
      max_parallel_workers_per_gather: "2"
    # Timescale defered : stubs SQL côté postInitSQL pour ce soir.
    # shared_preload_libraries:
    #   - timescaledb
  enableSuperuserAccess: true
