apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finance-tracker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Sylad/developpeur-gitops.git
    targetRevision: main
    path: charts/finance-tracker
    helm:
      releaseName: finance-tracker
  destination:
    server: https://kubernetes.default.svc
    namespace: preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
